### PR TITLE
Added Danish translation

### PR DESCRIPTION
**Pull request by VisualBean**

### CODE REVIEW

**Comment by cenan** [comment]
@VisualBean thank you for the translation. I would like to add you to the about box. Shall I use VisualBean or your real name?

**Comment by VisualBean** [comment]
No problem, it's a great thing you've made! - Just use my "handle" (VisualBean) :) Thanks

**Comment by cenan** [comment]
@VisualBean I have used VisualBean

I couldn't find your dbdesigner account from your user name. Can you please send a blank mail to info@dbdesigner.net from your dbdesigner account e-mail
I'm adding translators to a different account type.

**Comment by VisualBean** [comment]
Ive changed my username to reflect my usual handle - but I've also sent a blank mail to info@dbdesigner.net

**Pull request merged**
