### PR TITLE
Add Chinese(zh) translation

### PR DESCRIPTION
**Pull request by crunchysoul**
Add Chinese translation file: zh.js.coffee
Please accept the pull request after validation
Cheers, crunchysoul

### CODE REVIEW

**Comment by Ruegen** [comment]
Holy s*it - I really need this implemented for my Chinese clients!

**Comment by nisalVD** [comment]
awesome work really needed that!

**Comment by sooshaun** [comment]
This is awesome. Good job.

**Comment by miminum** [comment]
crunchy code!

**Comment by Nick-Son** [comment]
Awesome work Crunchy!

**Comment by ClaytonWong** [comment]
Good stuff Chen, love your work.

**Comment by cenan** [comment]
@crunchysoul thank you for the translation

**Pull request merged**
