### PR TITLE
Fix translation

### PR DESCRIPTION
**Pull request by tspoke**
Fix translation errors.

### CODE REVIEW

**Comment by cenan** [comment]
@tspoke Thank you for the fixes @connecttobn Thank you for the merge

**Comment by tspoke** [comment]
@cenan you are welcome.

I was passing on the repository because I am looking for a javascript library to do like dbdesigner: a graphic with the possibility of linking the keys between boxes. It's for a personal project and I do not find any good library to do it.
You have a canvas with nodes in DOM that you can connect. Did you use a library or you coded it yourself?
Thank you.

**Comment by cenan** [comment]
@tspoke I have coded the necessary bits myself from scratch. I have seen https://jsplumbtoolkit.com used by similar software, but AFAIK it uses SVG instead of canvas.

**Comment by tspoke** [comment]
@cenan Thank you, but the community edition is quite limited in features !
I think I'm gonna code it myself from scratch and maybe open-source it.

Thank you, good luck to you with dbdesigner, it's a great software ;)

**Pull request merged**
