### PR TITLE
All translated words to spanish

### PR DESCRIPTION
**Pull request by heurze**
Hi, i have translated all to spanish :D have a nice day Atte:. heurze

### CODE REVIEW

**Comment by cenan** [comment]
@heurze Thank you. I would like to add you to the about box. Do you want me to use your real name or shall I use "heurze" ?

**Comment by heurze** [comment]
heurze would be fine @cenan so much thanks ... :)

**Comment by heurze** [comment]
hello @cenan ,
how are you? i was thinking about the "about box" and i would like to know if you can change heurze for something like 
Juan Urbina (Heurze)
instead of, if it is not much trouble.
Best Regards,
heurze

**Comment by cenan** [comment]
Hi, @heurze I have changed it to
Juan Urbina (Heurze)

**Pull request merged**
