### PR TITLE
Added Brazilian Portuguese translation.

### PR DESCRIPTION
**Pull request by felladrin**

### CODE REVIEW

**Comment by cenan** [comment]
@felladrin Thank you

**Comment by felladrin** [comment]
Thank you too @cenan

**Comment by cenan** [comment]
I have deployed the changed version, and added you to the github team. This way you can merge your future changes. I have added your real name to the about box. If you want I can change it to your nick name.

**Comment by felladrin** [comment]
Thank you! It's alright.
I'll be watching the repo and will update the translation file as you add new fields.
Keep it up!

**Pull request merged**
